version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: search
      POSTGRES_PASSWORD: search
      POSTGRES_DB: search_logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres

  go-logger:
    build:
      context: ./go
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis

  python-logger:
    build:
      context: ./python
    ports:
      - "8082:8000"
    depends_on:
      - postgres
      - redis

  elixir-logger:
    build:
      context: ./elixir_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ecto://search:search@postgres/search_logs
    ports:
      - "4000:4000"

volumes:
  pgdata:
  redisdata:
  grafana-storage:
